name: Delete Older Releases

on:
  workflow_dispatch:

jobs:
  delete:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dev-drprasad/delete-older-releases@v0.2.0
        with:
          repo: AvirukBasak/JSHP
          keep_latest: 5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
